### ISSUE TITLE
Make &Vector useful without cloning

### ISSUE THREAD

**Issue by Diggsey** [pgvector/pgvector-rust#10]
At the moment, if you have a `&Vector`, there's no much you can do with it without first cloning it into a `Vec<f32>`. It would be convenient if we could iterate it, index into it, even compute cosine distances between vectors, without needing to do that cloning.

**Comment by ankane** [comment]
Hi @Diggsey, added an `as_slice` method in the commit above that should enable all of those.

**Comment by Diggsey** [comment]
Nice!
