### ISSUE TITLE
Unable to Use sqlx::query!() Macro

### ISSUE THREAD

**Issue by kahagerman** [pgvector/pgvector-rust#14]
From what I can tell, the built-in `Vector` type cannot be used with sqlx's `query!` macro.

The [sqlx examples](https://github.com/pgvector/pgvector-rust/blob/0911b9020c3c04f5ba9b3d75caf36a54db239d1b/README.md#sqlx) use the query function instead of the macro form.

When I try to do this:
```rust
let embedding = Vector::from(vec![1., 0., 0.]);

sqlx::query!("INSERT INTO items (embedding) VALUES ($1)", embedding)
```

I get the following error:
```
error: unsupported type vector for param #1
  --> src/main.rs:37:9
   |
37 |         sqlx::query!("INSERT INTO items (embedding) VALUES ($1)", embedding)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is this expected to work?

**Comment by ankane** [comment]
Hi @kahagerman, you'll need to use `embedding as Vector`:

```rust
sqlx::query!("INSERT INTO items (embedding) VALUES ($1)", embedding as Vector)
```

https://docs.rs/sqlx/latest/sqlx/macro.query.html#type-overrides-bind-parameters-postgres-only
