### ISSUE TITLE
Passing a slice of Vectors to a query using SQLx

### ISSUE THREAD

**Issue by matthewrobertbell** [pgvector/pgvector-rust#3]
Hi, very useful project, so first of all thank you!

I had an SQLx query that had a `&Option<Vector>` being passed to it as a parameter, and that worked great. I changed it to `&Option<Vec<pgvector::Vector>>` and it didn't work as `sqlx::postgres::PgHasArrayType` wasn't implemented for Vector. (exact types of my arguments are from memory, but in testing removing `Option` didn't fix it).

I managed to get it to work by vendoring this crate and adding this. The reason I haven't created a pull request is that I'm not sure if this approach is appropriate, but hopefully it helps support for slices of embeddings being passed as a parameter.

Code (in sqlx_ext.rs):

```
use sqlx::postgres::PgHasArrayType;
use sqlx::TypeInfo;

impl PgHasArrayType for Vector {
    fn array_type_info() -> PgTypeInfo {
        PgTypeInfo::with_name("_vector")
    }

    fn array_compatible(ty: &PgTypeInfo) -> bool {
        ty.name() == "_vector"
    }
}
```

**Comment by ankane** [comment]
Hi @matthewrobertbell, thanks for the suggestion! Added in the commit above. Do you know what `array_compatible` is needed for? The basic test case above seems to work without it.

**Comment by ankane** [comment]
Great, just pushed a new release (0.2.1). Thanks for figuring this out!
