### ISSUE TITLE
Vector not deriving serde::Serialize & serde::Deserialize

### ISSUE THREAD

**Issue by turulix** [pgvector/pgvector-rust#6]
As the title says, would it be possible to derive Serialize & Deserialize for the Vector, so you can simply Serialize it into a json string using serde?

**Comment by ankane** [comment]
Hi @turulix, thanks for the suggestion. I'd like to keep `Vector` simple (and focused on DB interactions), so think it's better to convert to/from `Vec<32>` for serialization.

**Comment by turulix** [comment]
Yes, but this requires a lot of work as a user since you have to manually convert between the Vector type and the Vec<f32>. This is a problem when using serde since there is no really clean way of doing this as far as im aware of. And deriving the two traits, this would be done automatically by serde. If you want to keep this simplistic, maybe put this feature behind a feature flag that isn't enabled by default but available as a quality or life feature

**Comment by turulix** [comment]
Made a fork which implements the Serialize & Deserialize in case you need it https://github.com/turulix/pgvector-rust

**Comment by turulix** [comment]
Oh sweet, i'm just gonna use yours then, since I didn't publish mine :)

**Comment by ankane** [comment]
Added a `serde` feature in the commit above (will go out with the next release)
