### ISSUE TITLE
Trait Bound Error on Vector Type when Using with SQLx: Vector: Encode<'_, _> and Vector: Type<_> Not Satisfied

### ISSUE THREAD

**Issue by danwritecode** [pgvector/pgvector-rust#7]
Hey All, I ran into an issue using sqlx with pgvector. 

I had an oldish repo (a couple months) where I used pgvector and despite seeing the same version (0.2.2) in each when running cargo tree, I noticed that pgvector was using sqlx version = 0.5.13 and my new repo was using sqlx version = 0.7.1 despite my cargo toml in the project specifying sqlx = 0.5.

I ended up forking pgvector and hardcoded the sqlx version to 0.5.13 to match the sqlx version used in my projects cargo.toml and it fixed the issue. 

Realizing this I upgraded my sqlx version of my primary project to 0.7 and went back to the actual pgvector crate (not my fork) and was also able to resolve the issue this way. 

It took me a bit to figure out this issue so I figured I would create and resolve an issue for posterity and sanity sake of future searchers.

```rust
        let rows = sqlx::query("SELECT * FROM brain_matter ORDER BY embedding <-> $1 LIMIT 1")
            .bind(Vector::from(embedding))
            .fetch_all(&self.pool)
            .await?;
```

Errors:
```
error[E0277]: the trait bound `Vector: Type<_>` is not satisfied
  --> src/services/db_service.rs:31:19
   |
31 |             .bind(Vector::from(embedding))
   |              ---- ^^^^^^^^^^^^^^^^^^^^^^^ the trait `Type<_>` is not implemented for `Vector`
   |              |
   |              required by a bound introduced by this call
   |
   = help: the following other types implement trait `Type<DB>`:
             <&T as Type<DB>>
             <() as Type<Postgres>>
             <(T1, T2) as Type<Postgres>>
             <(T1, T2, T3) as Type<Postgres>>
             <(T1, T2, T3, T4) as Type<Postgres>>
             <(T1, T2, T3, T4, T5) as Type<Postgres>>
             <(T1, T2, T3, T4, T5, T6) as Type<Postgres>>
             <(T1, T2, T3, T4, T5, T6, T7) as Type<Postgres>>
           and 27 others

error[E0277]: the trait bound `Vector: Encode<'_, _>` is not satisfied
  --> src/services/db_service.rs:31:19
   |
31 |             .bind(Vector::from(embedding))
   |              ---- ^^^^^^^^^^^^^^^^^^^^^^^ the trait `Encode<'_, _>` is not implemented for `Vector`
   |              |
   |              required by a bound introduced by this call
   |
   = help: the following other types implement trait `Encode<'q, DB>`:
             <&T as Encode<'q, DB>>
             <&[T] as Encode<'q, Postgres>>
             <&[u8] as Encode<'_, Postgres>>
             <&str as Encode<'_, Postgres>>
             <Cow<'_, str> as Encode<'_, Postgres>>
             <Duration as Encode<'_, Postgres>>
             <Option<T> as Encode<'q, Postgres>>
             <PgInterval as Encode<'_, Postgres>>
           and 17 others
```

**Comment by saintazunya** [comment]
Can I ask why is this closed? We also ran into this issue several weeks ago.

**Comment by InAnYan** [comment]
Hi, all!

I'm having this issue right know. @ankane should I recreate issue?

**Comment by InAnYan** [comment]
Looking in the `Cargo.toml`, the `sqlx` has version requirement something like ">= 0.5 && < 0.8", while I had exactly 0.8. 

If copied this version requirement from your crate to mine, and it seems to work

**Comment by ankane** [comment]
Added support for SQLx 0.8 in 117fb6675665751ccceee8491107492da2b30e72.

**Comment by InAnYan** [comment]
Thank you for the quick reply! Waiting for the release
